<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Kotresh" failures="1" tests="3" name="Test" time="102.012" errors="0" timestamp="2023-07-13T16:17:58 IST">
  <testcase classname="hrm.HRhead.DashBoardTest" name="dashboardtest" time="29.809"/>
  <testcase classname="hrm.HRhead.EmployeeTest" name="employeeTest" time="42.059"/>
  <testcase classname="hrm.HRhead.BranchTest" name="branchtest" time="3.845">
    <failure type="java.lang.AssertionError" message="expected [Failed] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [Failed] but found [true]
at hrm.HRhead.BranchTest.branchtest(BranchTest.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- branchtest -->
  <testcase classname="com.Estron.HRM.GenericUtility.BaseClass" name="@AfterSuite disconnectFromDatabase" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite disconnectFromDatabase -->
  <testcase classname="com.Estron.HRM.GenericUtility.BaseClass" name="@AfterSuite disconnectFromDatabase" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite disconnectFromDatabase -->
  <testcase classname="com.Estron.HRM.GenericUtility.BaseClass" name="@BeforeSuite connectionToDatabase" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite connectionToDatabase -->
  <testcase classname="com.Estron.HRM.GenericUtility.BaseClass" name="@BeforeSuite connectionToDatabase" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite connectionToDatabase -->
</testsuite> <!-- Test -->
